import { Case } from './models/condition.model';

export const EHR_FIXTURE =
	'The patient is a 32 year old female who presents to the Urgent Care complaining of sore throat that started 7 days ago. Developed into post nasal drip and then cough. No measured fevers. Had chills and body aches at the onset that resolved after the first day. A little facial headache with the congestion at times; better today. Some pressure on and off in the ears, no pain, hearing loss or tinnitus. Cough is mostly dry, sometimes productive of clear sputum. Denies shortness of breath. Never smoker. Has never needed inhalers. No history of pneumonia. Currently treating with ibuprofen which helps. Tried some over-the-counter Mucinex ES and vitamin C. The patient is a 32 year old female who presents to the Urgent Care complaining of sore throat that started 7 days ago. Developed into post nasal drip and then cough. No measured fevers. Had chills and body aches at the onset that resolved after the first day. A little facial headache with the congestion at times; better today. Some pressure on and off in the ears, no pain, hearing loss or tinnitus. Cough is mostly dry, sometimes productive of clear sputum. Denies shortness of breath. Never smoker. Has never needed inhalers. No history of pneumonia. Currently treating with ibuprofen which helps. Tried some over-the-counter Mucinex ES and vitamin C.The patient is a 32 year old female who presents to the Urgent Care complaining of sore throat that started 7 days ago. Developed into post nasal drip and then cough. No measured fevers. Had chills and body aches at the onset that resolved after the first day. A little facial headache with the congestion at times; better today. Some pressure on and off in the ears, no pain, hearing loss or tinnitus. Cough is mostly dry, sometimes productive of clear sputum. Denies shortness of breath. Never smoker. Has never needed inhalers. No history of pneumonia. Currently treating with ibuprofen which helps. Tried some over-the-counter Mucinex ES and vitamin C.';

export const CASES_FIXTURE: Case[] = [
	{
		description: EHR_FIXTURE,
		caseId: '10',
	},
];

export const CONDITIONS_FIXTURE = {
	ICD_10: 'ICD_10_Description',
	A09: 'Infectious gastroenteritis and colitis, unspecified',
	A64: 'Unspecified sexually transmitted disease',
	B300: 'Keratoconjunctivitis due to adenovirus',
	B302: 'Viral pharyngoconjunctivitis',
	B308: 'Other viral conjunctivitis',
	B309: 'Viral conjunctivitis, unspecified',
	B373: 'Candidiasis of vulva and vagina',
	B9789: 'Other viral agents as the cause of diseases classified elsewhere',
	E860: 'Dehydration',
	F340: 'Cyclothymic disorder',
	F341: 'Dysthymic disorder',
	F39: 'Unspecified mood [affective] disorder',
	F411: 'Generalized anxiety disorder',
	F418: 'Other specified anxiety disorders',
	F419: 'Anxiety disorder, unspecified',
	F4321: 'Adjustment disorder with depressed mood',
	G43001: 'Migraine without aura, not intractable, with status migrainosus',
	G43009: 'Migraine without aura, not intractable, without status migrainosus',
	G43019: 'Migraine without aura, intractable, without status migrainosus',
	G43501: 'Persistent migraine aura without cerebral infarction, not intractable, with status migrainosus',
	G43509: 'Persistent migraine aura without cerebral infarction, not intractable, without status migrainosus',
	G43519: 'Persistent migraine aura without cerebral infarction, intractable, without status migrainosus',
	G43701: 'Chronic migraine without aura, not intractable, with status migrainosus',
	G43709: 'Chronic migraine without aura, not intractable, without status migrainosus',
	G43711: 'Chronic migraine without aura, intractable, with status migrainosus',
	G43719: 'Chronic migraine without aura, intractable, without status migrainosus',
	G43809: 'Other migraine, not intractable, without status migrainosus',
	G43811: 'Other migraine, intractable, with status migrainosus',
	G43819: 'Other migraine, intractable, without status migrainosus',
	G43829: 'Menstrual migraine, not intractable, without status migrainosus',
	G43909: 'Migraine, unspecified, not intractable, without status migrainosus',
	G43911: 'Migraine, unspecified, intractable, with status migrainosus',
	G43919: 'Migraine, unspecified, intractable, without status migrainosus',
	G44209: 'Tension-type headache, unspecified, not intractable',
	G44219: 'Episodic tension-type headache, not intractable',
	H10029: 'Other mucopurulent conjunctivitis, unspecified eye',
	H60339: "Swimmer's ear, unspecified ear",
	H60399: 'Other infective otitis externa, unspecified ear',
	H66009: 'Acute suppurative otitis media without spontaneous rupture of ear drum, unspecified ear',
	H66019: 'Acute suppurative otitis media with spontaneous rupture of ear drum, unspecified ear',
	H663X9: 'Other chronic suppurative otitis media, unspecified ear',
	H10509: 'Unspecified blepharoconjunctivitis, unspecified eye',
	H10819: 'Pingueculitis, unspecified eye',
	H65119: 'Acute and subacute allergic otitis media (mucoid) (sanguinous) (serous), unspecified ear',
	H65199: 'Other acute nonsuppurative otitis media, unspecified ear',
	G4700: 'Insomnia, unspecified',
	G4701: 'Insomnia due to medical condition',
	G5600: 'Carpal tunnel syndrome, unspecified upper limb',
	H1033: 'Unspecified acute conjunctivitis, bilateral',
	H1044: 'Vernal conjunctivitis',
	H1045: 'Other chronic allergic conjunctivitis',
	H1089: 'Other conjunctivitis',
	H6020: 'Malignant otitis externa, unspecified ear',
	H6500: 'Acute serous otitis media, unspecified ear',
	H6520: 'Chronic serous otitis media, unspecified ear',
	H6590: 'Unspecified nonsuppurative otitis media, unspecified ear',
	H6640: 'Suppurative otitis media, unspecified, unspecified ear',
	H6690: 'Otitis media, unspecified, unspecified ear',
	L240: 'Irritant contact dermatitis due to detergents',
	L242: 'Irritant contact dermatitis due to solvents',
	L250: 'Unspecified contact dermatitis due to cosmetics',
	L251: 'Unspecified contact dermatitis due to drugs in contact with skin',
	L253: 'Unspecified contact dermatitis due to other chemical products',
	L255: 'Unspecified contact dermatitis due to plants, except food',
	L259: 'Unspecified contact dermatitis, unspecified cause',
	N730: 'Acute parametritis and pelvic cellulitis',
	N733: 'Female acute pelvic peritonitis',
	N739: 'Female pelvic inflammatory disease, unspecified',
	N912: 'Amenorrhea, unspecified',
	N920: 'Excessive and frequent menstruation with regular cycle',
	N921: 'Excessive and frequent menstruation with irregular cycle',
	N924: 'Excessive bleeding in the premenopausal period',
	N930: 'Postcoital and contact bleeding',
	N946: 'Dysmenorrhea, unspecified',
	R079: 'Chest pain, unspecified',
	R109: 'Unspecified abdominal pain',

	S53449A: 'Ulnar collateral ligament sprain of unspecified elbow, initial encounter',
	S63519A: 'Sprain of carpal joint of unspecified wrist, initial encounter',
	S63599A: 'Other specified sprain of unspecified wrist, initial encounter',
	S638X9A: 'Sprain of other part of unspecified wrist and hand, initial encounter',
	S93419A: 'Sprain of calcaneofibular ligament of unspecified ankle, initial encounter',
	S93429A: 'Sprain of deltoid ligament of unspecified ankle, initial encounter',
	S93439A: 'Sprain of tibiofibular ligament of unspecified ankle, initial encounter',
};
